### ISSUE TITLE
MoteLoadCurrentFile crashes

### ISSUE THREAD

**Issue by gilligan** [imeckler/auto#11]
Executing `:MoteLoadCurrentFile` I get the following output : 

```
Error detected while processing function mote#loadCurrentFile:                                                                                                                                               
line    1:                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                           
  File "<string>", line 1, in <module>                                                                                                                                                                       
  File "/home/gilligan/.vim/bundle/mote/vim/autoload/mote.py", line 241, in load_current_file                                                                                                                
    get_mote_process().load(vim.current.buffer.name)                                                                                                                                                         
  File "/home/gilligan/.vim/bundle/mote/vim/autoload/mote.py", line 210, in get_mote_process                                                                                                                 
    mote_process.start()                                                                                                                                                                                     
  File "/home/gilligan/.vim/bundle/mote/vim/autoload/mote.py", line 170, in start                                                                                                                            
    raise e                                                                                                                                                                                                  
OSError: [Errno 2] No such file or directory  
```

Let me know what additional info I can provide to track this down.

**Comment by gilligan** [comment]
Actually I was just being stupid - mote was not in my path because of a silly typo.
